#!/bin/sh
PREREQ=""
prereqs()
{
        echo "$PREREQ"
}
case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

PROFILE="profile init-systemd /lib/systemd/** flags=(complain) 
{
	/bin/mount cx -> bin_mount,
	/lib/netplan/generate cx -> netplan_profile,
	/sbin/udevadm cx -> udevadm_profile,
	/usr/bin/basename	cx -> basename_profile,
	/usr/lib/systemd/system-environment-generators/snapd-env-generator cx -> snapd_env_generator,
	/usr/lib/colord/color-sane cx -> colord_profile, 
	/usr/lib/colord/colord cx -> colord_profile, 
	/usr/lib/colord/color-session cx -> colord_profile, 

	capability audit_read,
	capability audit_write,	
	capability chown,
	capability dac_override,
	capability dac_read_search,
	capability kill,
	capability mknod,
	capability net_admin,
	capability setuid,
	capability sys_admin,
	capability sys_boot,
	capability sys_module,
	capability sys_ptrace,
	capability sys_resource,
	capability sys_time,
	capability sys_tty_config,

	/dev/** rw,
	/etc/**	r,

	/lib/console-setup/keyboard-setup.sh	rmix,	
	/lib/systemd/** rix,
	/lib/** rm,

	mount, 

	/proc/** rw,
	ptrace, 


	/run/**	rwcx -> run_default,
	signal, 

	/sys/** rwcx -> sys_default,
	
	/usr/ r,
	/{,usr/}{,s}bin/** rmwcx -> default_profile,
	/usr/lib/x86_64-linux-gnu/**	rm,
	/usr/** rw,
	/var/** rw,
	/tmp/** rw,
	

	profile run_default flags=(complain){

	}

	profile sys_default flags=(complain){

	}
	
	profile default_profile flags=(complain){
		/** rwmkix,
		signal,
		ptrace,
		mount,

		/{,usr/}{,s}bin/* r, 
		/dev/null	rw,
		/etc/ld.so.cache	r,
		/etc/locale.alias	r,
		/etc/udev/**	r,
		/lib/netplan/generate mr,
		/lib/modules/**	rw,
		/lib/x86_64-linux-gnu/*.so mr,
		/lib/x86_64-linux-gnu/*.so.* mr,
		/proc/**	r,
		ptrace,
		/run/systemd/generator/openvpn.service.wants/	rw,
		/run/systemd/generator/openvpn.service.wants/**	rw,
		/run/tmpfiles.d/	rw,
		/run/tmpfiles.d/**	rw,
		/sys/module/**	r,
		/usr/lib/locale/**	r,
		/usr/lib/x86_64-linux-gnu/*.so.* rm,
		/usr/share/locale-langpack/**	r,
	}
	profile netplan_profile flags=(complain) {
		capability mknod,
		/bin/udevadm	rix,
		/dev/null	rw,
		/etc/ld.so.cache	r,
		/etc/netplan/	r,
		/etc/netplan/**	r,
		/etc/udev/** r,
		/lib/netplan/	r,
		/lib/netplan/generate mrix,
		/lib/systemd/system-generators/netplan	mrix,
		/lib/x86_64-linux-gnu/*.so mr,
		/lib/x86_64-linux-gnu/*.so.* mr,
		/proc/** r,
		ptrace,
		/run/NetworkManager/ rw,
		/run/NetworkManager/** rw,
		/run/systemd/** rw,
		/usr/lib/x86_64-linux-gnu/*.so.* rm,
	}
	profile snapd_env_generator flags=(complain) {
		/dev/null	rw,
		/etc/ld.so.cache	r, 
		/lib/x86_64-linux-gnu/*.so mr,
		/lib/x86_64-linux-gnu/*.so.* mr,
		/usr/lib/systemd/system-environment-generators/snapd-env-generator mr,
	}
	profile bin_mount flags=(complain) {
		capability sys_admin,
		mount, 
		/bin/mount	rm,	
		/dev/loop-control	rw,
		/dev/** r,
		/etc/ld.so.cache	r,
		/etc/locale.alias	r,
		/lib/x86_64-linux-gnu/*.so mr,
		/lib/x86_64-linux-gnu/*.so.* mr,
		/proc/**	r,
		/run/mount/	rw,
		/run/mount/**	rkw,
		/sys/devices/**	r,
		/usr/lib/x86_64-linux-gnu/*.so.* rm,
		/var/lib/**	r,
	}
	profile udevadm_profile flags=(complain) {
		
	}
	
	profile colord_profile {
		/dev/**	r,
		/etc/ld.so.cache	r, 
		/lib/x86_64-linux-gnu/*.so mr,
		/lib/x86_64-linux-gnu/*.so.* mr,
		/sys/**	r,
		/run/**	r,
		/usr/lib/x86_64-linux-gnu/*.so.* rm,
		/usr/lib/colord/**	mrix,
	}
	profile basename_profile flags=(complain){
		/lib/x86_64-linux-gnu/ld-*.so mr,
		/usr/bin/basename mr,
		/etc/ld.so.cache  r,
		/lib/x86_64-linux-gnu/*.so mr,
		/lib/x86_64-linux-gnu/*.so.* mr,
		/home/abhishek/.local/share/gvfs-metadata/**  r,
		/usr/share/code/**    r,
		/dev/**   wr,

	}
}"

mount -t securityfs none /sys/kernel/security
#echo "profile init-systemd /lib/systemd/** flags=(complain) {/lib/systemd/* ix, /{,usr/}{,s}bin/* pix, /opt/** Px,}" | /sbin/apparmor_parser -a
#echo "profile init-upstart /sbin/upstart flags=(complain) {}" | /sbin/apparmor_parser -a

echo "$PROFILE" | /sbin/apparmor_parser -a
#echo "profile init-upstart /sbin/upstart flags=(complain) {}" | /sbin/apparmor_parser -a

read -p "Enter a name: " name
echo "Hi, $name"
